version: '3.8'

services:
  # FastAPI Application Service
  api:
    build: .
    ports:
      - "8000:80" # Map host port 8000 to container port 80
    volumes:
      - ./app:/code/app # Mount local 'app' directory into the container for live-reloading
    env_file:
      - ./.env # Pass environment variables from .env file
    depends_on:
      - db # This service depends on the 'db' service to be running

  # PostgreSQL Database Service
  db:
    image: postgres:14-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/ # Persist database data
    expose:
      - 5432 # Expose port 5432 to other services in the network, but not to the host machine
    env_file:
      - ./.env # Use .env for postgres user, password, and db name

  # pgAdmin Service for Database Management (Optional but very useful)
  pgadmin:
    image: dpage/pgadmin4
    env_file:
      - ./.env # Use .env for pgAdmin email and password
    ports:
      - "5050:80" # Map host port 5050 to pgAdmin's container port 80
    depends_on:
      - db

volumes:
  postgres_data: # Define the named volume for data persistence
