"""Add bogie checksheet models

Revision ID: d91e48807859
Revises: ec970fdee17b
Create Date: 2025-07-26 13:31:51.128543

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd91e48807859'
down_revision: Union[str, Sequence[str], None] = 'ec970fdee17b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('bogie_checksheet_forms',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('formNumber', sa.String(), nullable=False),
    sa.Column('inspectionBy', sa.String(), nullable=False),
    sa.Column('inspectionDate', sa.Date(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_bogie_checksheet_forms_formNumber'), 'bogie_checksheet_forms', ['formNumber'], unique=True)
    op.create_index(op.f('ix_bogie_checksheet_forms_id'), 'bogie_checksheet_forms', ['id'], unique=False)
    op.create_table('bmbc_checksheets',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('form_id', sa.Integer(), nullable=True),
    sa.Column('cylinderBody', sa.String(), nullable=True),
    sa.Column('pistonTrunnion', sa.String(), nullable=True),
    sa.Column('adjustingTube', sa.String(), nullable=True),
    sa.Column('plungerSpring', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['form_id'], ['bogie_checksheet_forms.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_bmbc_checksheets_id'), 'bmbc_checksheets', ['id'], unique=False)
    op.create_table('bogie_checksheets',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('form_id', sa.Integer(), nullable=True),
    sa.Column('bogieFrameCondition', sa.String(), nullable=True),
    sa.Column('bolster', sa.String(), nullable=True),
    sa.Column('bolsterSuspensionBracket', sa.String(), nullable=True),
    sa.Column('lowerSpringSeat', sa.String(), nullable=True),
    sa.Column('axleGuide', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['form_id'], ['bogie_checksheet_forms.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_bogie_checksheets_id'), 'bogie_checksheets', ['id'], unique=False)
    op.create_table('bogie_details',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('form_id', sa.Integer(), nullable=True),
    sa.Column('bogieNo', sa.String(), nullable=True),
    sa.Column('makerYearBuilt', sa.String(), nullable=True),
    sa.Column('incomingDivAndDate', sa.String(), nullable=True),
    sa.Column('deficitComponents', sa.String(), nullable=True),
    sa.Column('dateOfIOH', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['form_id'], ['bogie_checksheet_forms.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_bogie_details_id'), 'bogie_details', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_bogie_details_id'), table_name='bogie_details')
    op.drop_table('bogie_details')
    op.drop_index(op.f('ix_bogie_checksheets_id'), table_name='bogie_checksheets')
    op.drop_table('bogie_checksheets')
    op.drop_index(op.f('ix_bmbc_checksheets_id'), table_name='bmbc_checksheets')
    op.drop_table('bmbc_checksheets')
    op.drop_index(op.f('ix_bogie_checksheet_forms_id'), table_name='bogie_checksheet_forms')
    op.drop_index(op.f('ix_bogie_checksheet_forms_formNumber'), table_name='bogie_checksheet_forms')
    op.drop_table('bogie_checksheet_forms')
    # ### end Alembic commands ###
