"""Initial migration for forms

Revision ID: ec970fdee17b
Revises: 
Create Date: 2025-07-26 00:02:52.117614

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ec970fdee17b'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('wheel_specifications',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('formNumber', sa.String(), nullable=False),
    sa.Column('submittedBy', sa.String(), nullable=False),
    sa.Column('submittedDate', sa.Date(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_wheel_specifications_formNumber'), 'wheel_specifications', ['formNumber'], unique=True)
    op.create_index(op.f('ix_wheel_specifications_id'), 'wheel_specifications', ['id'], unique=False)
    op.create_table('wheel_specification_fields',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('form_id', sa.Integer(), nullable=True),
    sa.Column('treadDiameterNew', sa.String(), nullable=True),
    sa.Column('lastShopIssueSize', sa.String(), nullable=True),
    sa.Column('condemningDia', sa.String(), nullable=True),
    sa.Column('wheelGauge', sa.String(), nullable=True),
    sa.Column('variationSameAxle', sa.String(), nullable=True),
    sa.Column('variationSameBogie', sa.String(), nullable=True),
    sa.Column('variationSameCoach', sa.String(), nullable=True),
    sa.Column('wheelProfile', sa.String(), nullable=True),
    sa.Column('intermediateWWP', sa.String(), nullable=True),
    sa.Column('bearingSeatDiameter', sa.String(), nullable=True),
    sa.Column('rollerBearingOuterDia', sa.String(), nullable=True),
    sa.Column('rollerBearingBoreDia', sa.String(), nullable=True),
    sa.Column('rollerBearingWidth', sa.String(), nullable=True),
    sa.Column('axleBoxHousingBoreDia', sa.String(), nullable=True),
    sa.Column('wheelDiscWidth', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['form_id'], ['wheel_specifications.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_wheel_specification_fields_id'), 'wheel_specification_fields', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_wheel_specification_fields_id'), table_name='wheel_specification_fields')
    op.drop_table('wheel_specification_fields')
    op.drop_index(op.f('ix_wheel_specifications_id'), table_name='wheel_specifications')
    op.drop_index(op.f('ix_wheel_specifications_formNumber'), table_name='wheel_specifications')
    op.drop_table('wheel_specifications')
    # ### end Alembic commands ###
